# Generated by Django 2.0.1 on 2018-01-16 04:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='conference_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=120)),
                ('conference_acronym', models.CharField(max_length=20)),
                ('conference_webpage', models.URLField()),
                ('conference_venue', models.CharField(max_length=120)),
                ('conference_city', models.CharField(max_length=100)),
                ('conference_country', django_countries.fields.CountryField(max_length=2)),
                ('conference_start', models.DateField()),
                ('conference_end', models.DateField()),
                ('conference_organizer', models.CharField(max_length=120)),
                ('conference_organizer_webpage', models.CharField(max_length=120)),
                ('conference_organizer_contact', models.IntegerField()),
                ('conference_research_area', models.CharField(max_length=120)),
                ('conference_area_notes', models.TextField()),
                ('conference_other_info', models.TextField()),
                ('conference_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
